# Generated by Django 5.2.6 on 2025-09-20 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
        ('orders_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='offers_app.offerdetail'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['offer_detail'], name='orders_app__offer_d_2b558a_idx'),
        ),
    ]
