# Generated by Django 5.2.6 on 2025-09-17 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='working_hours',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
